// Curated list of major cities for autocomplete suggestions.
// Format: "City, State" or "City, Country" — display label only.

export const CITY_SUGGESTIONS: string[] = [
  // United States — most likely
  'Las Vegas, NV',
  'Los Angeles, CA',
  'New York, NY',
  'Miami, FL',
  'Chicago, IL',
  'Houston, TX',
  'Phoenix, AZ',
  'Philadelphia, PA',
  'San Antonio, TX',
  'San Diego, CA',
  'Dallas, TX',
  'San Jose, CA',
  'Austin, TX',
  'Jacksonville, FL',
  'Fort Worth, TX',
  'Columbus, OH',
  'Charlotte, NC',
  'San Francisco, CA',
  'Indianapolis, IN',
  'Seattle, WA',
  'Denver, CO',
  'Washington, DC',
  'Boston, MA',
  'El Paso, TX',
  'Nashville, TN',
  'Detroit, MI',
  'Oklahoma City, OK',
  'Portland, OR',
  'Memphis, TN',
  'Louisville, KY',
  'Milwaukee, WI',
  'Baltimore, MD',
  'Albuquerque, NM',
  'Tucson, AZ',
  'Fresno, CA',
  'Sacramento, CA',
  'Mesa, AZ',
  'Kansas City, MO',
  'Atlanta, GA',
  'Long Beach, CA',
  'Colorado Springs, CO',
  'Raleigh, NC',
  'Omaha, NE',
  'Virginia Beach, VA',
  'Oakland, CA',
  'Minneapolis, MN',
  'Tampa, FL',
  'Tulsa, OK',
  'Arlington, TX',
  'New Orleans, LA',
  'Wichita, KS',
  'Cleveland, OH',
  'Bakersfield, CA',
  'Aurora, CO',
  'Anaheim, CA',
  'Honolulu, HI',
  'Santa Ana, CA',
  'Riverside, CA',
  'Corpus Christi, TX',
  'Lexington, KY',
  'Stockton, CA',
  'Henderson, NV',
  'Saint Paul, MN',
  'St. Louis, MO',
  'Cincinnati, OH',
  'Pittsburgh, PA',
  'Greensboro, NC',
  'Anchorage, AK',
  'Plano, TX',
  'Lincoln, NE',
  'Orlando, FL',
  'Irvine, CA',
  'Newark, NJ',
  'Toledo, OH',
  'Durham, NC',
  'Chula Vista, CA',
  'Fort Wayne, IN',
  'Jersey City, NJ',
  'St. Petersburg, FL',
  'Laredo, TX',
  'Madison, WI',
  'Chandler, AZ',
  'Buffalo, NY',
  'Lubbock, TX',
  'Scottsdale, AZ',
  'Reno, NV',
  'Glendale, AZ',
  'Gilbert, AZ',
  'Winston-Salem, NC',
  'North Las Vegas, NV',
  'Norfolk, VA',
  'Chesapeake, VA',
  'Garland, TX',
  'Irving, TX',
  'Hialeah, FL',
  'Fremont, CA',
  'Boise, ID',
  'Richmond, VA',
  'Baton Rouge, LA',
  'Spokane, WA',
  'Des Moines, IA',
  'Tacoma, WA',
  'San Bernardino, CA',
  'Modesto, CA',
  'Fontana, CA',
  'Santa Clarita, CA',
  'Birmingham, AL',
  'Oxnard, CA',
  'Fayetteville, NC',
  'Moreno Valley, CA',
  'Rochester, NY',
  'Glendale, CA',
  'Huntington Beach, CA',
  'Salt Lake City, UT',
  'Grand Rapids, MI',
  'Worcester, MA',
  'Knoxville, TN',
  'Brownsville, TX',
  'Newport News, VA',
  'Overland Park, KS',
  'Santa Rosa, CA',
  'Providence, RI',
  'Garden Grove, CA',
  'Chattanooga, TN',
  'Oceanside, CA',
  'Jackson, MS',
  'Fort Lauderdale, FL',
  'Rancho Cucamonga, CA',
  'Santa Clara, CA',
  'Vancouver, WA',
  'Tempe, AZ',
  'Sioux Falls, SD',
  'Springfield, MO',
  'Peoria, AZ',
  'Pembroke Pines, FL',
  'Elk Grove, CA',
  'Salem, OR',
  'Lancaster, CA',
  'Corona, CA',
  'Eugene, OR',
  'Palmdale, CA',
  'Salinas, CA',
  'Springfield, MA',
  'Pasadena, TX',
  'Fort Collins, CO',
  'Hayward, CA',
  'Pomona, CA',
  'Cary, NC',
  'Rockford, IL',
  'Alexandria, VA',
  'Escondido, CA',
  'McKinney, TX',
  'Kansas City, KS',
  'Joliet, IL',
  'Sunnyvale, CA',
  'Torrance, CA',
  'Bridgeport, CT',
  'Lakewood, CO',
  'Hollywood, FL',
  'Paterson, NJ',
  'Naperville, IL',
  'Syracuse, NY',
  'Mesquite, TX',
  'Dayton, OH',
  'Savannah, GA',
  'Clarksville, TN',
  'Orange, CA',
  'Pasadena, CA',
  'Fullerton, CA',
  'Killeen, TX',
  'Frisco, TX',
  'Hampton, VA',
  'McAllen, TX',
  'Warren, MI',
  'Bellevue, WA',
  'West Valley City, UT',
  'Columbia, SC',
  'Olathe, KS',
  'Sterling Heights, MI',
  'New Haven, CT',
  'Miramar, FL',
  'Waco, TX',
  'Thousand Oaks, CA',
  'Cedar Rapids, IA',
  'Charleston, SC',
  'Visalia, CA',
  'Topeka, KS',
  'Elizabeth, NJ',
  'Gainesville, FL',
  'Thornton, CO',
  'Roseville, CA',
  'Carrollton, TX',
  'Coral Springs, FL',
  'Stamford, CT',
  'Simi Valley, CA',
  'Concord, CA',
  'Hartford, CT',
  'Kent, WA',
  'Lafayette, LA',
  'Midland, TX',
  'Surprise, AZ',
  'Denton, TX',
  'Victorville, CA',
  'Evansville, IN',
  'Santa Clara, CA',
  'Abilene, TX',
  'Athens, GA',
  'Vallejo, CA',
  'Allentown, PA',
  'Norman, OK',
  'Beaumont, TX',
  'Independence, MO',
  'Murfreesboro, TN',
  'Ann Arbor, MI',
  'Springfield, IL',
  'Berkeley, CA',
  'Peoria, IL',
  'Provo, UT',
  'El Monte, CA',
  'Columbia, MO',
  'Lansing, MI',
  'Fargo, ND',
  'Downey, CA',
  'Costa Mesa, CA',
  'Wilmington, NC',
  'Arvada, CO',
  'Inglewood, CA',
  'Miami Gardens, FL',
  'Carlsbad, CA',
  'Westminster, CO',
  'Rochester, MN',
  'Odessa, TX',
  'Manchester, NH',
  'Elgin, IL',
  'West Jordan, UT',
  'Round Rock, TX',
  'Clearwater, FL',
  'Waterbury, CT',
  'Gresham, OR',
  'Fairfield, CA',
  'Billings, MT',
  'Lowell, MA',
  'Ventura, CA',
  'Pueblo, CO',
  'High Point, NC',
  'West Covina, CA',
  'Richmond, CA',
  'Murrieta, CA',
  'Cambridge, MA',
  'Antioch, CA',
  'Temecula, CA',
  'Norwalk, CA',
  'Centennial, CO',
  'Everett, WA',
  'Palm Bay, FL',
  'Wichita Falls, TX',
  'Green Bay, WI',
  'Daly City, CA',
  'Burbank, CA',
  'Richardson, TX',
  'Pompano Beach, FL',
  'North Charleston, SC',
  'Broken Arrow, OK',
  'Boulder, CO',
  'West Palm Beach, FL',
  'Santa Maria, CA',
  'El Cajon, CA',
  'Davenport, IA',
  'Rialto, CA',
  'Edison, NJ',
  'Las Cruces, NM',
  'San Mateo, CA',
  'Lewisville, TX',
  'South Bend, IN',
  'Lakeland, FL',
  'Erie, PA',
  'Tyler, TX',
  'Pearland, TX',
  'College Station, TX',
  'Kenosha, WI',
  'Sandy Springs, GA',
  'Clovis, CA',
  'Flint, MI',
  'Roanoke, VA',
  'Albany, NY',
  'Jurupa Valley, CA',
  'Compton, CA',
  'San Angelo, TX',
  'Hillsboro, OR',
  'Lawton, OK',
  'Renton, WA',
  'Vista, CA',
  'Davie, FL',
  'Greeley, CO',
  'Mission Viejo, CA',
  'Portsmouth, VA',
  'Dearborn, MI',
  'South Gate, CA',
  'Tuscaloosa, AL',
  'Livonia, MI',
  'New Bedford, MA',
  'Vacaville, CA',
  'Brockton, MA',
  'Roswell, GA',
  'Beaverton, OR',
  'Quincy, MA',
  'Sparks, NV',
  'Yonkers, NY',
  'Aspen, CO',
  'Park City, UT',
  'Nantucket, MA',
  'Martha\u2019s Vineyard, MA',
  'East Hampton, NY',
  'Southampton, NY',
  'Montauk, NY',
  // International
  'London, UK',
  'Paris, France',
  'Milan, Italy',
  'Rome, Italy',
  'Madrid, Spain',
  'Barcelona, Spain',
  'Berlin, Germany',
  'Amsterdam, Netherlands',
  'Copenhagen, Denmark',
  'Stockholm, Sweden',
  'Oslo, Norway',
  'Dublin, Ireland',
  'Lisbon, Portugal',
  'Athens, Greece',
  'Vienna, Austria',
  'Zurich, Switzerland',
  'Geneva, Switzerland',
  'Brussels, Belgium',
  'Prague, Czech Republic',
  'Budapest, Hungary',
  'Warsaw, Poland',
  'Istanbul, Turkey',
  'Tokyo, Japan',
  'Kyoto, Japan',
  'Osaka, Japan',
  'Seoul, South Korea',
  'Hong Kong',
  'Singapore',
  'Bangkok, Thailand',
  'Dubai, UAE',
  'Abu Dhabi, UAE',
  'Tel Aviv, Israel',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Auckland, New Zealand',
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Mexico City, Mexico',
  'São Paulo, Brazil',
  'Rio de Janeiro, Brazil',
  'Buenos Aires, Argentina',
  'Cape Town, South Africa',
  'Johannesburg, South Africa',
  'Marrakesh, Morocco',
  'Mumbai, India',
  'Delhi, India',
]
